# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
weight = 1
identifier = "github"
name = "GitHub"
url = "https://github.com"

[social.params]
icon = "brand-github"

[[social]]
weight = 2
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com"

[social.params]
icon = "brand-twitter"

[[social]]
weight = 3
identifier = "emojis"
name = "serach-emojis"
url = "https://www.emojisearch.app/"

[social.params]
icon = "search"
newtab = true